spring.application.name=ExamJEE
spring.datasource.url=jdbc:postgresql://localhost:5432/assurance_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.data.jdbc.dialect=postgresql
spring.jpa.hibernate.ddl-auto=create

server.port=9095

